name: fiap-first-challenge

services:
  postgre:
    image: bitnami/postgresql:16.3.0
    volumes:
      - pg-fastfood:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=fastfood
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d fastfood"]
      interval: 3s
      timeout: 5s
      retries: 5

  back-end:
    # image: lucasnoman/fastfood-backend:${IMAGE_VERSION}
    build: ./
    volumes:
      - type: bind
        source: "/Users/lucasnoman/Documents/Dev/Codes/FIAP/Fase_1/Tech Challenge Refeito/fast-food"
        target: /usr/src/app
        # Exclude node_modules from volume
      - type: volume
        source: node-modules
        target: /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
    networks:
      - app-network
    depends_on:
      postgre:
        condition: service_healthy

volumes:
  pg-fastfood:
  node-modules:

networks:
  app-network:
